print("       *****       ")
print("    **       **    ")
print("  **           **  ")
print(" **             ** ")
print(" **    0   0    ** ")
print(" **       -     ** ")
print("   **  \___/  **   ")
print("     **     **     ")
print("       *****       ")
